### ISSUE TITLE
config.duration null error

### ISSUE THREAD

**Issue by beev** [devbobo/homebridge-lifx-lan#2]
Hi. I'm baffled by this error. I've installed homebridge and it was working prior to the installation of my first plugin. That is, it was offering me a pin number and asking to be connected to a home kit app. Once I installed the lifx plugin and ran homebridge again, I got the following error. 

```
[3/13/2016, 1:33:26 PM] Loaded plugin: homebridge-lifx-lan
[3/13/2016, 1:33:26 PM] Registering platform 'homebridge-lifx-lan.LifxLan'
[3/13/2016, 1:33:26 PM] ---
Load homebridge-lifx-lan.LifxLan
/usr/local/lib/node_modules/homebridge-lifx-lan/index.js:64
    fadeDuration = config.duration || 1000;
                         ^

TypeError: Cannot read property 'duration' of null
    at new LifxLanPlatform (/usr/local/lib/node_modules/homebridge-lifx-lan/index.js:64:26)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:73:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

```

The contents of my config.json file are below. The file is inside the homebridge dir, it was created in bash as a duplicate of config-sample.json, and I haven't opened it in anything other than Atom. I added the "duration" variable to "platforms" to see if it would make any difference, but the error is the same regardless.

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
            "accessory": "LIFX Bulb",
            "name": "Light Bulb"
        }
    ],

    "platforms": [
        {
            "platform" : "LifxLan",
            "name" : "LiFx",
            "duration" : "1000"
        }
    ]
}

```

Any help much appreciated!

**Comment by devbobo** [comment]
@beev sorry, I get a load of work related github notifications, so sometimes I miss ones from my personal projects.

I've just committed a [fix](https://github.com/devbobo/homebridge-lifx-lan/commit/41f3b328f1621c906cd52d018789433a25167e7a) which should resolve the issue.

Also, your `duration` parameter should be an `integer` rather than a `string`

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
            "accessory": "LIFX Bulb",
            "name": "Light Bulb"
        }
    ],

    "platforms": [
        {
            "platform" : "LifxLan",
            "name" : "LiFx",
            "duration" : 1000
        }
    ]
}
```
