### ISSUE TITLE
Avoid initializing plugin if not in config.json

### ISSUE THREAD

**Issue by alexymik** [devbobo/homebridge-lifx-lan#35]
Hi,

I noticed today when setting up another homebridge instance to split some of my accessories, that this plugin (installed globally) was trying to setup another node-lifx Client even though I did not add the plugin to the `"platforms"` section.

Error log:

```
LIFX Client UDP error
Trace: { Error: bind EADDRINUSE 0.0.0.0:56700
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at _handle.lookup (dgram.js:266:18)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 56700 }
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:147:13)
    at Socket.emit (events.js:159:13)
    at _handle.lookup (dgram.js:267:14)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

I was able to work around this by having the instance I needed to control the lights with start before the other and ignoring the error. 

I also needed to add this change:

```javascript
LifxLanPlatform.prototype.configureAccessory = function(accessory) {
    if (typeof(this.accessories) != 'undefined') { this.accessories[accessory.UUID] = accessory; }
}
```

I realize I could probably avoid these issues by installing homebridge locally for multiple users, but is there a possibility to change the plugin to initialize only if it's used?

**Comment by devbobo** [comment]
@alexymik what version of the plugin are you currently using ?

I implemented a fix for this back in version `0.2.2` (current version `0.2.6`).

**Comment by devbobo** [comment]
Closing...please reopen if this is still an issue.

**Comment by alexymik** [comment]
Sorry for the late reply -- had to investigate why my lights weren't coming on after a power failure and ran into this issue again.

Checking the version, it's `0.2.6`. To be sure I removed and re-added from npm.
