### ISSUE TITLE
this.accessory.on is not a function

### ISSUE THREAD

**Issue by tommack** [devbobo/homebridge-lifx-lan#8]
homebridge-lifx-lan@0.1.2

I saw this error today:

```
[8/7/2016, 8:22:13 PM] [LiFx] Online: undefined [d073d5010a86]
/usr/local/lib/node_modules/homebridge-lifx-lan/index.js:394
    this.accessory.on('identify', function(paired, callback) {
                   ^

TypeError: this.accessory.on is not a function
    at new LifxAccessory (/usr/local/lib/node_modules/homebridge-lifx-lan/index.js:394:20)
    at /usr/local/lib/node_modules/homebridge-lifx-lan/index.js:126:42
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/light.js:127:14)
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:370:24)
    at Array.forEach (native)
    at Client.processMessageHandlers (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:341:24)
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:178:12)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:532:8)

```

**Comment by nider** [comment]
Me too today, it came after an undefined light name in the logs

```
[9/7/2016, 12:39:17 AM] [homebridge-lifx-lan.LifxLan] Online: undefined [d073d513df6e]
/Users/darktemplar/node_modules/homebridge-lifx-lan/index.js:394
    this.accessory.on('identify', function(paired, callback) {
                   ^

TypeError: this.accessory.on is not a function
    at new LifxAccessory (/Users/darktemplar/node_modules/homebridge-lifx-lan/index.js:394:20)
    at /Users/darktemplar/node_modules/homebridge-lifx-lan/index.js:126:42
    at Client.<anonymous> (/Users/darktemplar/node_modules/node-lifx/lib/lifx/light.js:127:14)
    at Client.<anonymous> (/Users/darktemplar/node_modules/node-lifx/lib/lifx/client.js:370:24)
    at Array.forEach (native)
    at Client.processMessageHandlers (/Users/darktemplar/node_modules/node-lifx/lib/lifx/client.js:341:24)
    at Client.<anonymous> (/Users/darktemplar/node_modules/node-lifx/lib/lifx/client.js:178:12)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:550:8)
```

**Comment by devbobo** [comment]
I've just released version 0.1.3, can you please give it a go and see if it resolves your issue. 👍

**Comment by nider** [comment]
~~So far seems good, I haven't had it crash since updating 👍~~

I spoke too soon:

```
[9/22/2016, 1:39:14 AM] [homebridge-lifx-lan.LifxLan] Offline: Bed head Test [d073d513df6e]
[9/22/2016, 1:42:19 AM] [homebridge-lifx-lan.LifxLan] Online: undefined [d073d513df6e]
/Users/darktemplar/node_modules/homebridge-lifx-lan/index.js:394
    this.accessory.on('identify', function(paired, callback) {
                   ^

TypeError: this.accessory.on is not a function
    at new LifxAccessory (/Users/darktemplar/node_modules/homebridge-lifx-lan/index.js:394:20)
    at /Users/darktemplar/node_modules/homebridge-lifx-lan/index.js:126:42
    at Client.<anonymous> (/Users/darktemplar/node_modules/node-lifx/lib/lifx/light.js:127:14)
    at Client.<anonymous> (/Users/darktemplar/node_modules/node-lifx/lib/lifx/client.js:370:24)
    at Array.forEach (native)
    at Client.processMessageHandlers (/Users/darktemplar/node_modules/node-lifx/lib/lifx/client.js:341:24)
    at Client.<anonymous> (/Users/darktemplar/node_modules/node-lifx/lib/lifx/client.js:178:12)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:550:8)
```
