### ISSUE TITLE
LIFX Client UDP error

### ISSUE THREAD

**Issue by jbadnes** [devbobo/homebridge-lifx-lan#9]
Cant wait to use this. When I install I get this error ?

`Load homebridge-lifx-lan.LifxLan
LIFX Client UDP error
Trace: { [Error: bind EADDRINUSE 0.0.0.0:56700]
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 56700 }
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:147:13)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at dgram.js:215:14
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
`

**Comment by jbadnes** [comment]
Looked like the port was taken for some reason. I cleared my cache and WOW its working. Fantastic plugin. Still testing but looks like its up and working now.

**Comment by devbobo** [comment]
ok, cool...can I close this issue ?

**Comment by jbadnes** [comment]
Yes thank you

On Sep 8, 2016, at 8:30 AM, David Parry <notifications@github.com<mailto:notifications@github.com>> wrote:

ok, cool...can I close this issue ?

##

**Comment by bentoscano** [comment]
I'm also having this exact error, but find myself markedly less savvy than OP. Can anyone guide me on how I can clear this port to be able to use this plugin?

`LIFX Client UDP error
Trace: { [Error: bind EADDRINUSE 0.0.0.0:56700]
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 56700 }
    at Client.<anonymous> (/Users/bentoscano/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:147:13)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at dgram.js:214:14
    at doNTCallback3 (node.js:452:9)
    at process._tickCallback (node.js:358:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3`

**Comment by dereitz** [comment]
bentoscano - did you ever fix this?  I'm having the same issue.  Thanks!

**Comment by bentoscano** [comment]
dereitz - I remember trying a plethora of things and can't remember exactly how I fixed it, sorry about that! If I do recall, I'll reply here.

**Comment by dereitz** [comment]
Thanks, in my case, I believe that OpenHAB is already using that port.  I'm just not sure how to change the port that LIFX uses or what side effects that will have.

**Comment by fpg1503** [comment]
I had this issue because I was using the LIFX component, changing the homebridge default visibility to `visiblie` did the trick (no need to use this plugin). The LIFX component was already using the port 56700.
